FROM node:14-alpine AS development
ENV NODE_ENV development
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .

# Copy app files
COPY . .

# Start the app
CMD [ "yarn", "start" ]